---
- name: Install aerospace via homebrew on MacOS
  community.general.homebrew_cask:
    name:
      - nikitabobko/tap/aerospace
    state: present
  when: ansible_distribution == "MacOSX"

- name: Create "$HOME/.config/aerospace" directory if not exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME')  }}/.config/{{ role_name }}"
    mode: "0755"
    state: directory
  when: ansible_distribution == "MacOSX"

- name: Create symlink of files to "$HOME/.config/aerospace" directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ lookup('env', 'HOME')  }}/.config/{{ role_name }}"
    state: link
    force: true
  when: ansible_distribution == "MacOSX"
